---
- name: Update firmware on Cisco device
  hosts: localhost
  vars:
    cisco_version: "1.3"
    firmware_dir: "/home/student1"
    firmware_version: "1.3"
    firmware_file_name: "firmware-update-1.3"
    firmware_file_path: "{{ firmware_dir }}/{{ firmware_file_name }}"
  tasks:
  - set_fact:
      md5_value: "{{ lookup('file', '{{ firmware_file_path }}.md5') }}"

  - debug:
      msg: "Firmware md5 is: {{ md5_value }}"

  - name: Calculate checksum from file
    stat:
      path: "{{ firmware_file_path }}"
      checksum_algorithm: md5
    register: firmware

  - name:
    debug:
      msg: "Calculated: {{ firmware.stat.checksum }}"

  - debug:
      msg: "Firmware has an invalid checksum"
    when: ( firmware.stat.checksum != md5_value )

